# Generated by Django 4.2.7 on 2025-10-25 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do cliente', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email do cliente', max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, help_text='Telefone do cliente', max_length=20, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, help_text='CPF ou CNPJ do cliente', max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, help_text='Endereço do cliente', max_length=300, null=True)),
                ('cidade', models.CharField(blank=True, help_text='Cidade do cliente', max_length=100, null=True)),
                ('estado', models.CharField(blank=True, help_text='Estado (UF) do cliente', max_length=2, null=True)),
                ('cep', models.CharField(blank=True, help_text='CEP do cliente', max_length=10, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se o cliente está ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(help_text='Usuário proprietário do cliente', on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-criado_em'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da marca do produto', max_length=100, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do produto', null=True)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço unitário do produto', max_digits=10)),
                ('estoque', models.IntegerField(default=0, help_text='Quantidade em estoque')),
                ('ativo', models.BooleanField(default=True, help_text='Se o produto está ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(blank=True, help_text='Marca do produto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='vendas.marca')),
                ('usuario', models.ForeignKey(help_text='Usuário proprietário do produto', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-criado_em'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True, help_text='Data e hora da venda')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, help_text='Valor total da venda', max_digits=12)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto'), ('pix', 'PIX'), ('cheque', 'Cheque'), ('outro', 'Outro')], default='dinheiro', help_text='Forma de pagamento', max_length=20)),
                ('data_vencimento', models.DateField(help_text='Data de vencimento do pagamento')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a venda', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente da venda', on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='vendas.client')),
                ('usuario', models.ForeignKey(help_text='Usuário proprietário da venda', on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Quantidade vendida')),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço unitário no momento da venda', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, help_text='Subtotal do item (quantidade x preço)', max_digits=12)),
                ('produto', models.ForeignKey(help_text='Produto vendido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_venda', to='vendas.product')),
                ('venda', models.ForeignKey(help_text='Venda à qual o item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.sale')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor a receber', max_digits=12)),
                ('data_vencimento', models.DateField(help_text='Data de vencimento')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data do pagamento (preenchido quando pago)', null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('vencido', 'Vencido'), ('pago', 'Pago')], default='pendente', help_text='Status da conta', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(help_text='Cliente devedor', on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='vendas.client')),
                ('usuario', models.ForeignKey(help_text='Usuário proprietário', on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to=settings.AUTH_USER_MODEL)),
                ('venda', models.OneToOneField(help_text='Venda relacionada', on_delete=django.db.models.deletion.CASCADE, related_name='conta_receber', to='vendas.sale')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição do boleto/pagamento', max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor a pagar', max_digits=12)),
                ('data_vencimento', models.DateField(help_text='Data de vencimento')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data do pagamento (preenchido quando pago)', null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('vencido', 'Vencido'), ('pago', 'Pago')], default='pendente', help_text='Status da conta', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='Usuário proprietário', on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
