# Generated by Django 4.2.7 on 2025-10-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsreceivable',
            name='venda',
            field=models.ForeignKey(help_text='Venda relacionada', on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber_venda', to='vendas.sale'),
        ),
    ]
